name: varta
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  flutter_bloc: ^8.1.1
  flutter_webrtc: ^0.9.16
  get_it: ^7.2.0
  path_provider: ^2.0.11
  video_player: ^2.4.7
  wakelock: ^0.6.2
  cloud_firestore: ^4.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
