// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHguFXz4Iy2gABmFSU7bFky9N65qM2kq4',
    appId: '1:490785565400:web:a6909e06ccbb45e6a485ad',
    messagingSenderId: '490785565400',
    projectId: 'varta-86032',
    authDomain: 'varta-86032.firebaseapp.com',
    storageBucket: 'varta-86032.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6o20dEOgFIo1QkFz-HrFeffP30c1Hdwk',
    appId: '1:490785565400:android:8c4d8e479c95d2e1a485ad',
    messagingSenderId: '490785565400',
    projectId: 'varta-86032',
    storageBucket: 'varta-86032.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEQqvDXITek7WWl9qFpHH6BOaycGRynys',
    appId: '1:490785565400:ios:77b127a15d6df659a485ad',
    messagingSenderId: '490785565400',
    projectId: 'varta-86032',
    storageBucket: 'varta-86032.appspot.com',
    iosClientId: '490785565400-125orkt6dcfj8pfi7ldrvirgf771ccn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.varta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEQqvDXITek7WWl9qFpHH6BOaycGRynys',
    appId: '1:490785565400:ios:77b127a15d6df659a485ad',
    messagingSenderId: '490785565400',
    projectId: 'varta-86032',
    storageBucket: 'varta-86032.appspot.com',
    iosClientId: '490785565400-125orkt6dcfj8pfi7ldrvirgf771ccn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.varta',
  );
}
